apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-sonar-sentry-creator"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: post-install
        image: bitnami/kubectl:latest
        command: ["/bin/bash", "-c"]
        args:
        - |
          kubectl get pods -o wide
        env:
        - name: GUID_PREFIX
          value: "{{ include "sonar-sentry-daemonset.guidPrefix" . }}"
        volumeMounts:
        - mountPath: /etc/secrets
          name: secret-volume
          readOnly: true  
      restartPolicy: Never
      volumes:
      - name: secret-volume
        secret:
          secretName: sentry-secrets