apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sonar-sentry-daemonset.fullname" . }}-loggers
  labels:
    {{- include "sonar-sentry-daemonset.labels" . | nindent 4 }}
data:
  loggers.json: |
    {
      "loggers": {{ .Values.sonar.loggers | toJson }}
    } 