apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "sonar-sentry-daemonset.fullname" . }}
  labels:
    {{- include "sonar-sentry-daemonset.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sonar-sentry-daemonset.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sonar-sentry-daemonset.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sonar-sentry-daemonset.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "public.ecr.aws/z5g1b4t8/sonar-sentry-dev:1.1.8"
          imagePullPolicy: Always
          ports:
            - name: sentry-diag
              containerPort: 7022
              protocol: TCP
            - name: sentry-syslog
              containerPort: 514
              protocol: UDP
          envFrom:
          - secretRef:
              name: {{ .Values.sonar.secret.name }}
          env:
            - name: DEPLOY_URL
              value: "{{- .Values.sonar.deployUrl -}}"
            - name: BASE_ADDR
              value: "{{- .Values.sonar.baseAddr -}}"
            - name: "SENTRY_GUID_PREFIX"
              value: "{{- include "sonar-sentry-daemonset.guidPrefix" . -}}"
            - name: CONTROL_API_PORT
              value: "{{ default 443 .Values.sonar.controlApiPort }}"
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- with .Values.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/root/shutdown.sh"]
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
