apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sonar-sentry-daemonset-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sonar-sentry-daemonset.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "sonar-sentry-daemonset.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: sonar-sentry-daemonset-role
  apiGroup: rbac.authorization.k8s.io