apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sonar-sentry-daemonset-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sonar-sentry-daemonset.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["resourcequotas"]
  verbs: ["get", "list", "create", "delete"]
