apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.sonar.secret.namespace }}
  name: {{ .Values.sonar.secret.name }}
type: Opaque
data:
  SENTRY_AUTH_TOKEN: {{ .Values.sonar.sentryAuthToken | b64enc | quote }}
  SONAR_API_KEY: {{ .Values.sonar.sonarApiKey | b64enc | quote }}